-- Create database
CREATE DATABASE IF NOT EXISTS ProductCatalog;
USE ProductCatalog;

-- Create table for categories
CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Create table for subcategories
CREATE TABLE IF NOT EXISTS subcategories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) UNIQUE,
    category_id INT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Create table for products
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    subcategory_id INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(id)
);

create view if not exists products_view as
select 
    products.name as name, 
    categories.name as category, 
    subcategories.name as subcategory,
    products.price as price
from 
    products inner join subcategories on products.subcategory_id = subcategories.id 
    inner join categories on subcategories.category_id = categories.id 
order by products.name;

insert into categories (name) values
    ("Tubería sanitaria"),
    ("Accesorios sanitarios"),
    ("Accesorios PVC"),
    ("Tubería PVC"),
    ("Tubería CPVC"),
    ("Soldadura de plomería"),
    ("Limpiador de plomería"),
    ("Accesorios CPVC"),
    ("Tubería eléctrica"),
    ("Accesorios para tubería eléctrica"),
    ("Canaletas eléctricas"),
    ("Canales y accesorios"),
    ("Tubos cortineros"),
    ("Accesorios para tubo cortinero"),
    ("Ángulos, perfiles y platinas de hierro"),
    ("Mallas"),
    ("Piraguas"),
    ("Cables eléctricos"),
    ("Alambres galvanizados"),
    ("Soldadura eléctrica"),
    ("Ángulos esquineros para pared"),
    ("Herramientas"),
    ("Cable de acero"),
    ("Cocina"),
    ("Fibras y cordinos"),
    ("Polvos"),
    ("Impermeabilizantes");

insert into subcategories (name, category_id) values
    ("Tubo pesado", (select id from categories where name = "Tubería sanitaria")),
    ("Tubo semipesado", (select id from categories where name = "Tubería sanitaria")),
    ("Tubo liviano agualluvia", (select id from categories where name = "Tubería sanitaria")),
    ("Codo sanitario", (select id from categories where name = "Accesorios sanitarios")),
    ("Tee sanitaria", (select id from categories where name = "Accesorios sanitarios")),
    ("Unión sanitaria", (select id from categories where name = "Accesorios sanitarios")),
    ("Semicodo sanitario", (select id from categories where name = "Accesorios sanitarios")),
    ("Yee sanitaria", (select id from categories where name = "Accesorios sanitarios")),
    ("Tapón de prueba sanitario", (select id from categories where name = "Accesorios sanitarios")),
    ("Tapón limpieza", (select id from categories where name = "Accesorios sanitarios")),
    ("Junta de expansión", (select id from categories where name = "Accesorios sanitarios")),
    ("Rejilla PVC", (select id from categories where name = "Accesorios PVC")),
    ("Unión PVC", (select id from categories where name = "Accesorios PVC")),
    ("Tee PVC", (select id from categories where name = "Accesorios PVC")),
    ("Codo PVC", (select id from categories where name = "Accesorios PVC")),
    ("Adaptador hembra PVC", (select id from categories where name = "Accesorios PVC")),
    ("Adaptador macho PVC", (select id from categories where name = "Accesorios PVC")),
    ("Tubo PVC", (select id from categories where name = "Tubería PVC")),
    ("Tubo CPVC", (select id from categories where name = "Tubería CPVC")),
    ("Soldadura PVC", (select id from categories where name = "Soldadura de plomería")),
    ("Soldadura CPVC", (select id from categories where name = "Soldadura de plomería")),
    ("Limpiador PVC", (select id from categories where name = "Limpiador de plomería")),
    ("Unión CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Codo CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Tee CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Adaptador hembra CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Adaptador macho CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Tapón CPVC", (select id from categories where name = "Accesorios CPVC")),
    ("Tubo conduit certificado", (select id from categories where name = "Tubería eléctrica")),
    ("Tubo conduit económico", (select id from categories where name = "Tubería eléctrica")),
    ("Tubo SH40", (select id from categories where name = "Tubería eléctrica")),
    ("Tubo EMT", (select id from categories where name = "Tubería eléctrica")),
    ("Caja RETIE metálica", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Caja plástica", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Curva conduit fina", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Curva conduit económica", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Terminal conduit fino", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Terminal conduit económica", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Curva SH40", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Terminal SH40", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Curva EMT", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Terminal EMT", (select id from categories where name = "Accesorios para tubería eléctrica")),
    ("Canaleta eléctrica Dexon", (select id from categories where name = "Canaletas eléctricas")),
    ("Canaleta eléctrica económica", (select id from categories where name = "Canaletas eléctricas")),
    ("Tapa externa", (select id from categories where name = "Canales y accesorios")),
    ("Tapa interna", (select id from categories where name = "Canales y accesorios")),
    ("Unión canal", (select id from categories where name = "Canales y accesorios")),
    ("Unión bajante", (select id from categories where name = "Canales y accesorios")),
    ("Soporte canal", (select id from categories where name = "Canales y accesorios")),
    ("Unión esquinera para canal", (select id from categories where name = "Canales y accesorios")),
    ("Soporte de metal para canal", (select id from categories where name = "Canales y accesorios")),
    ("Sello de caucho para canal", (select id from categories where name = "Canales y accesorios")),
    ("Tubo bajante cuadrado", (select id from categories where name = "Canales y accesorios")),
    ("Canal", (select id from categories where name = "Canales y accesorios")),
    ("Tubo cortinero café", (select id from categories where name = "Tubos cortineros")),
    ("Tubo cortinero dorado", (select id from categories where name = "Tubos cortineros")),
    ("Soporte sencillo café", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Soporte sencillo dorado", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Soporte doble café", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Soporte doble dorado", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Plafón café", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Plafón dorado", (select id from categories where name = "Accesorios para tubo cortinero")),
    ("Ángulos de hierro calibre 18", (select id from categories where name = "Ángulos, perfiles y platinas de hierro")),
    ("Ángulos de hierro calibre 20", (select id from categories where name = "Ángulos, perfiles y platinas de hierro")),
    ("Perfiles de hierro calibre 18", (select id from categories where name = "Ángulos, perfiles y platinas de hierro")),
    ("Perfiles de hierro calibre 20", (select id from categories where name = "Ángulos, perfiles y platinas de hierro")),
    ("Platinas de hierro", (select id from categories where name = "Ángulos, perfiles y platinas de hierro")),
    ("Mallas plásticas", (select id from categories where name = "Mallas")),
    ("Mallas galvanizadas", (select id from categories where name = "Mallas")),
    ("Piragua de aluminio", (select id from categories where name = "Piraguas")),
    ("Cable duplex", (select id from categories where name = "Cables eléctricos")),
    ("Alambre en barra", (select id from categories where name = "Cables eléctricos")),
    ("Cable 7 hilos", (select id from categories where name = "Cables eléctricos")),
    ("Alambre negro", (select id from categories where name = "Alambres galvanizados")),
    ("Alambre galvanizado", (select id from categories where name = "Alambres galvanizados")),
    ("Soldadura eléctrica Lincon", (select id from categories where name = "Soldadura eléctrica")),
    ("Ángulo plástico", (select id from categories where name = "Ángulos esquineros para pared")),
    ("Herramientas para construcción", (select id from categories where name = "Herramientas")),
    ("Lavaplatos", (select id from categories where name = "Cocina")),
    ("Cable de acero trenzado", (select id from categories where name = "Cable de acero")),
    ("Bandejas para pintura", (select id from categories where name = "Herramientas")),
    ("Rodillos", (select id from categories where name = "Herramientas")),
    ("Cordino", (select id from categories where name = "Fibras y cordinos")),
    ("Fibra plástica", (select id from categories where name = "Fibras y cordinos")),
    ("Cemento", (select id from categories where name = "Polvos")),
    ("Estuco", (select id from categories where name = "Polvos")),
    ("Boquilla", (select id from categories where name = "Polvos")),
    ("Pegaenchape y aditivos", (select id from categories where name = "Polvos")),
    ("Impermeabilizante en polvo", (select id from categories where name = "Impermeabilizantes")),
    ("Yeso", (select id from categories where name = "Polvos"));


insert into products (name, subcategory_id, price) values
    ("Tubo pesado 1 1/2 x 6 metros", (select id from subcategories where name = "Tubo pesado"), 27500),
    ("Tubo pesado 1 1/2 x 1 metro", (select id from subcategories where name = "Tubo pesado"), 5600),
    ("Tubo pesado 2 x 6 metros", (select id from subcategories where name = "Tubo pesado"), 38600),
    ("Tubo pesado 2 x 1 metro", (select id from subcategories where name = "Tubo pesado"), 7500),
    ("Tubo pesado 3 x 6 metros", (select id from subcategories where name = "Tubo pesado"), 58000),
    ("Tubo pesado 3 x 1 metro", (select id from subcategories where name = "Tubo pesado"), 10500),
    ("Tubo pesado 4 x 6 metros", (select id from subcategories where name = "Tubo pesado"), 84000),
    ("Tubo pesado 4 x 1 metro", (select id from subcategories where name = "Tubo pesado"), 15000),
    ("Tubo pesado 6 x 6 metros", (select id from subcategories where name = "Tubo pesado"), 0),
    ("Tubo pesado 6 x 1 metro", (select id from subcategories where name = "Tubo pesado"), 0),
    ("Tubo semipesado 1 1/2 x 6 metros", (select id from subcategories where name = "Tubo semipesado"), 21800),
    ("Tubo semipesado 1 1/2 x 1 metro", (select id from subcategories where name = "Tubo semipesado"), 6000),
    ("Tubo semipesado 2 x 6 metros", (select id from subcategories where name = "Tubo semipesado"), 27500),
    ("Tubo semipesado 2 x 1 metro", (select id from subcategories where name = "Tubo semipesado"), 6800),
    ("Tubo semipesado 3 x 6 metros", (select id from subcategories where name = "Tubo semipesado"), 43500),
    ("Tubo semipesado 3 x 1 metro", (select id from subcategories where name = "Tubo semipesado"), 8500),
    ("Tubo semipesado 4 x 6 metros", (select id from subcategories where name = "Tubo semipesado"), 59800),
    ("Tubo semipesado 4 x 1 metro", (select id from subcategories where name = "Tubo semipesado"), 11500),
    ("Tubo semipesado 6 x 6 metros", (select id from subcategories where name = "Tubo semipesado"), 0),
    ("Tubo semipesado 6 x 1 metro", (select id from subcategories where name = "Tubo semipesado"), 0),
    ("Tubo liviano agualluvia 1 1/2 x 6 metros", (select id from subcategories where name = "Tubo liviano agualluvia"), 17500),
    ("Tubo liviano agualluvia 1 1/2 x 1 metro", (select id from subcategories where name = "Tubo liviano agualluvia"), 6000),
    ("Tubo liviano agualluvia 2 x 6 metros", (select id from subcategories where name = "Tubo liviano agualluvia"), 22500),
    ("Tubo liviano agualluvia 2 x 1 metro", (select id from subcategories where name = "Tubo liviano agualluvia"), 5800),
    ("Tubo liviano agualluvia 3 x 6 metros", (select id from subcategories where name = "Tubo liviano agualluvia"), 32800),
    ("Tubo liviano agualluvia 3 x 1 metro", (select id from subcategories where name = "Tubo liviano agualluvia"), 7500),
    ("Tubo liviano agualluvia 4 x 6 metros", (select id from subcategories where name = "Tubo liviano agualluvia"), 45000),
    ("Tubo liviano agualluvia 4 x 1 metro", (select id from subcategories where name = "Tubo liviano agualluvia"), 9500),
    ("Tubo liviano agualluvia 6 x 6 metros", (select id from subcategories where name = "Tubo liviano agualluvia"), 140000),
    ("Tubo liviano agualluvia 6 x 1 metro", (select id from subcategories where name = "Tubo liviano agualluvia"), 30000),
    ("Codo sanitario 1 1/2", (select id from subcategories where name = "Codo sanitario"), 2000),
    ("Codo sanitario 2", (select id from subcategories where name = "Codo sanitario"), 2500),
    ("Codo sanitario 3", (select id from subcategories where name = "Codo sanitario"), 5800),
    ("Codo sanitario 4", (select id from subcategories where name = "Codo sanitario"), 9800),
    ("Codo sanitario 6", (select id from subcategories where name = "Codo sanitario"), 49800),
    ("Tee sanitaria 1 1/2", (select id from subcategories where name = "Tee sanitaria"), 2900),
    ("Tee sanitaria 2", (select id from subcategories where name = "Tee sanitaria"), 3200),
    ("Tee sanitaria 3", (select id from subcategories where name = "Tee sanitaria"), 6800),
    ("Tee sanitaria 4", (select id from subcategories where name = "Tee sanitaria"), 10800),
    ("Tee sanitaria 6", (select id from subcategories where name = "Tee sanitaria"), 66000),
    ("Unión sanitaria 1 1/2", (select id from subcategories where name = "Unión sanitaria"), 1500),
    ("Unión sanitaria 2", (select id from subcategories where name = "Unión sanitaria"), 2000),
    ("Unión sanitaria 3", (select id from subcategories where name = "Unión sanitaria"), 4000),
    ("Unión sanitaria 4", (select id from subcategories where name = "Unión sanitaria"), 4800),
    ("Unión sanitaria 6", (select id from subcategories where name = "Unión sanitaria"), 22000),
    ("Semicodo sanitario 1 1/2", (select id from subcategories where name = "Semicodo sanitario"), 2650),
    ("Semicodo sanitario 2", (select id from subcategories where name = "Semicodo sanitario"), 3000),
    ("Semicodo sanitario 3", (select id from subcategories where name = "Semicodo sanitario"), 6800),
    ("Semicodo sanitario 4", (select id from subcategories where name = "Semicodo sanitario"), 8900),
    ("Semicodo sanitario 6", (select id from subcategories where name = "Semicodo sanitario"), 32500),
    ("Yee sanitaria 1 1/2", (select id from subcategories where name = "Yee sanitaria"), 8200),
    ("Yee sanitaria 2", (select id from subcategories where name = "Yee sanitaria"), 9200),
    ("Yee sanitaria 3", (select id from subcategories where name = "Yee sanitaria"), 12000),
    ("Yee sanitaria 4", (select id from subcategories where name = "Yee sanitaria"), 18900),
    ("Yee sanitaria 6", (select id from subcategories where name = "Yee sanitaria"), 66000),
    ("Tapón de prueba sanitario 1 1/2", (select id from subcategories where name = "Tapón de prueba sanitario"), 1000),
    ("Tapón de prueba sanitario 2", (select id from subcategories where name = "Tapón de prueba sanitario"), 1800),
    ("Tapón de prueba sanitario 3", (select id from subcategories where name = "Tapón de prueba sanitario"), 2500),
    ("Tapón de prueba sanitario 4", (select id from subcategories where name = "Tapón de prueba sanitario"), 3000),
    ("Tapón de prueba sanitario 6", (select id from subcategories where name = "Tapón de prueba sanitario"), 42000),
    ("Tapón limpieza 1 1/2", (select id from subcategories where name = "Tapón limpieza"), 0),
    ("Tapón limpieza 2", (select id from subcategories where name = "Tapón limpieza"), 6200),
    ("Tapón limpieza 3", (select id from subcategories where name = "Tapón limpieza"), 10800),
    ("Tapón limpieza 4", (select id from subcategories where name = "Tapón limpieza"), 13800),
    ("Tapón limpieza 6", (select id from subcategories where name = "Tapón limpieza"), 0),
    ("Junta de expansión 1 1/2", (select id from subcategories where name = "Junta de expansión"), 0),
    ("Junta de expansión 2", (select id from subcategories where name = "Junta de expansión"), 12000),
    ("Junta de expansión 3", (select id from subcategories where name = "Junta de expansión"), 16000),
    ("Junta de expansión 4", (select id from subcategories where name = "Junta de expansión"), 21800),
    ("Junta de expansión 6", (select id from subcategories where name = "Junta de expansión"), 0),
    ("Rejilla PVC 3 x 1 1/2", (select id from subcategories where name = "Rejilla PVC"), 4500),
    ("Rejilla PVC 3 x 2", (select id from subcategories where name = "Rejilla PVC"), 4500),
    ("Rejilla PVC 4 x 3", (select id from subcategories where name = "Rejilla PVC"), 6800),
    ("Unión PVC 1/2", (select id from subcategories where name = "Unión PVC"), 900),
    ("Unión PVC 3/4", (select id from subcategories where name = "Unión PVC"), 1200),
    ("Unión PVC 1", (select id from subcategories where name = "Unión PVC"), 1800),
    ("Unión PVC 1 1/2", (select id from subcategories where name = "Unión PVC"), 3600),
    ("Unión PVC 2", (select id from subcategories where name = "Unión PVC"), 4800),
    ("Tee PVC 1/2", (select id from subcategories where name = "Tee PVC"), 1200),
    ("Tee PVC 3/4", (select id from subcategories where name = "Tee PVC"), 1800),
    ("Tee PVC 1", (select id from subcategories where name = "Tee PVC"), 3200),
    ("Tee PVC 1 1/2", (select id from subcategories where name = "Tee PVC"), 11500),
    ("Tee PVC 2", (select id from subcategories where name = "Tee PVC"), 18400),
    ("Codo PVC 1/2", (select id from subcategories where name = "Codo PVC"), 900),
    ("Codo PVC 3/4", (select id from subcategories where name = "Codo PVC"), 1200),
    ("Codo PVC 1", (select id from subcategories where name = "Codo PVC"), 2900),
    ("Codo PVC 1 1/2", (select id from subcategories where name = "Codo PVC"), 8800),
    ("Codo PVC 2", (select id from subcategories where name = "Codo PVC"), 14400),
    ("Adaptador hembra PVC 1/2", (select id from subcategories where name = "Adaptador hembra PVC"), 900),
    ("Adaptador hembra PVC 3/4", (select id from subcategories where name = "Adaptador hembra PVC"), 1300),
    ("Adaptador hembra PVC 1", (select id from subcategories where name = "Adaptador hembra PVC"), 2800),
    ("Adaptador hembra PVC 1 1/2", (select id from subcategories where name = "Adaptador hembra PVC"), 6800),
    ("Adaptador hembra PVC 2", (select id from subcategories where name = "Adaptador hembra PVC"), 12100),
    ("Adaptador macho PVC 1/2", (select id from subcategories where name = "Adaptador macho PVC"), 900),
    ("Adaptador macho PVC 3/4", (select id from subcategories where name = "Adaptador macho PVC"), 1300),
    ("Adaptador macho PVC 1", (select id from subcategories where name = "Adaptador macho PVC"), 2800),
    ("Adaptador macho PVC 1 1/2", (select id from subcategories where name = "Adaptador macho PVC"), 5200),
    ("Adaptador macho PVC 2", (select id from subcategories where name = "Adaptador macho PVC"), 7300),
    ("Tubo PVC 1/2 x 6 metros", (select id from subcategories where name = "Tubo PVC"), 12950),
    ("Tubo PVC 1/2 x 1 metro", (select id from subcategories where name = "Tubo PVC"), 3000),
    ("Tubo PVC 3/4 x 6 metros", (select id from subcategories where name = "Tubo PVC"), 18800),
    ("Tubo PVC 3/4 x 1 metro", (select id from subcategories where name = "Tubo PVC"), 4000),
    ("Tubo PVC 1 x 6 metros", (select id from subcategories where name = "Tubo PVC"), 24600),
    ("Tubo PVC 1 x 1 metro", (select id from subcategories where name = "Tubo PVC"), 4800),
    ("Tubo CPVC 1/2 x 3 metros PAVCO", (select id from subcategories where name = "Tubo CPVC"), 24000),
    ("Tubo CPVC 1/2 x 3 metros Gerfor", (select id from subcategories where name = "Tubo CPVC"), 19500),
    ("Tubo CPVC 1/2 x 1 metro PAVCO", (select id from subcategories where name = "Tubo CPVC"), 9500),
    ("Tubo CPVC 1/2 x 1 metro Gerfor", (select id from subcategories where name = "Tubo CPVC"), 9500),
    ("Soldadura PVC 1/256", (select id from subcategories where name = "Soldadura PVC"), 3000),
    ("Soldadura PVC 1/128", (select id from subcategories where name = "Soldadura PVC"), 6500),
    ("Soldadura PVC 1/64", (select id from subcategories where name = "Soldadura PVC"), 11400),
    ("Soldadura PVC 1/32", (select id from subcategories where name = "Soldadura PVC"), 19800),
    ("Soldadura PVC 1/16", (select id from subcategories where name = "Soldadura PVC"), 29600),
    ("SOldadura PVC 1/8", (select id from subcategories where name = "Soldadura PVC"), 58000),
    ("Soldadura PVC 1/4", (select id from subcategories where name = "Soldadura PVC"), 92000),
    ("Soldadura CPVC 1/128", (select id from subcategories where name = "Soldadura CPVC"), 8200),
    ("Soldadura CPVC 1/64", (select id from subcategories where name = "Soldadura CPVC"), 13200),
    ("Soldadura CPVC 1/32", (select id from subcategories where name = "Soldadura CPVC"), 22500),
    ("Soldadura CPVC 1/16", (select id from subcategories where name = "Soldadura CPVC"), 38900),
    ("Limpiador PVC 1/128", (select id from subcategories where name = "Limpiador PVC"), 4500),
    ("Limpiador PVC 1/64", (select id from subcategories where name = "Limpiador PVC"), 6900),
    ("Limpiador PVC 1/32", (select id from subcategories where name = "Limpiador PVC"), 8700),
    ("Unión CPVC 1/2", (select id from subcategories where name = "Unión CPVC"), 1500),
    ("Unión CPVC 3/4", (select id from subcategories where name = "Unión CPVC"), 2100),
    ("Codo CPVC 1/2", (select id from subcategories where name = "Codo CPVC"), 1900),
    ("Codo CPVC 3/4", (select id from subcategories where name = "Codo CPVC"), 3600),
    ("Tee CPVC 1/2", (select id from subcategories where name = "Tee CPVC"), 2600),
    ("Tee CPVC 3/4", (select id from subcategories where name = "Tee CPVC"), 4100),
    ("Adaptador hembra CPVC 1/2", (select id from subcategories where name = "Adaptador hembra CPVC"), 3300),
    ("Adaptador hembra CPVC 3/4", (select id from subcategories where name = "Adaptador hembra CPVC"), 4000),
    ("Adaptador macho CPVC 1/2", (select id from subcategories where name = "Adaptador macho CPVC"), 2100), 
    ("Adaptador macho CPVC 3/4", (select id from subcategories where name = "Adaptador macho CPVC"), 2900),
    ("Tapón CPVC 1/2", (select id from subcategories where name = "Tapón CPVC"), 1900),
    ("Tubo conduit certificado 1/2", (select id from subcategories where name = "Tubo conduit certificado"), 5900),
    ("Tubo conduit certificado 3/4", (select id from subcategories where name = "Tubo conduit certificado"), 7200),
    ("Tubo conduit certificado 1", (select id from subcategories where name = "Tubo conduit certificado"), 9800),
    ("Tubo conduit certificado 1 1/2", (select id from subcategories where name = "Tubo conduit certificado"), 21500),
    ("Tubo conduit certificado 2", (select id from subcategories where name = "Tubo conduit certificado"), 34000),
    ("Tubo conduit económico 1/2", (select id from subcategories where name = "Tubo conduit económico"), 3500),
    ("Caja RETIE metálica 2 x 4", (select id from subcategories where name = "Caja RETIE metálica"), 2950),
    ("Caja RETIE metálica 4 x 4", (select id from subcategories where name = "Caja RETIE metálica"), 3950),
    ("Caja RETIE metálica Hexagonal", (select id from subcategories where name = "Caja RETIE metálica"), 3650),
    ("Caja plástica 2 x 4", (select id from subcategories where name = "Caja plástica"), 700),
    ("Caja plástica 4 x 4", (select id from subcategories where name = "Caja plástica"), 1200),
    ("Caja plástica Hexagonal", (select id from subcategories where name = "Caja plástica"), 900),
    ("Curva conduit económica 1/2", (select id from subcategories where name = "Curva conduit económica"), 600),
    ("Curva conduit fina 1/2", (select id from subcategories where name = "Curva conduit fina"), 950),
    ("Curva conduit fina 3/4", (select id from subcategories where name = "Curva conduit fina"), 1300),
    ("Curva conduit fina 1", (select id from subcategories where name = "Curva conduit fina"), 2600),
    ("Terminal conduit económica 1/2", (select id from subcategories where name = "Terminal conduit económica"), 450),
    ("Terminal conduit fino 1/2", (select id from subcategories where name = "Terminal conduit fino"), 650),
    ("Terminal conduit fino 3/4", (select id from subcategories where name = "Terminal conduit fino"), 850),
    ("Terminal conduit fino 1", (select id from subcategories where name = "Terminal conduit fino"), 1500),
    ("Terminal conduit fino 1 1/2", (select id from subcategories where name = "Terminal conduit fino"), 4000),
    ("Terminal conduit fino 2", (select id from subcategories where name = "Terminal conduit fino"), 6100),
    ("Tubo SH40 1/2", (select id from subcategories where name = "Tubo SH40"), 14250),
    ("Tubo SH40 3/4", (select id from subcategories where name = "Tubo SH40"), 18900),
    ("Tubo SH40 1", (select id from subcategories where name = "Tubo SH40"), 28200),
    ("Curva SH40 1/2", (select id from subcategories where name = "Curva SH40"), 2300),
    ("Curva SH40 3/4", (select id from subcategories where name = "Curva SH40"), 4300),
    ("Curva SH40 1", (select id from subcategories where name = "Curva SH40"), 7500),
    ("Terminal SH40 1/2", (select id from subcategories where name = "Terminal SH40"), 900),
    ("Terminal SH40 3/4", (select id from subcategories where name = "Terminal SH40"), 1300),
    ("Terminal SH40 1", (select id from subcategories where name = "Terminal SH40"), 7400),
    ("Tubo EMT 1/2 x 3 metros", (select id from subcategories where name = "Tubo EMT"), 16800),
    ("Tubo EMT 3/4 x 3 metros", (select id from subcategories where name = "Tubo EMT"), 22800),
    ("Tubo EMT 1 x 3 metros", (select id from subcategories where name = "Tubo EMT"), 48000),
    ("Curva EMT 1/2", (select id from subcategories where name = "Curva EMT"), 2600),
    ("Curva EMT 3/4", (select id from subcategories where name = "Curva EMT"), 3200),
    ("Curva EMT 1", (select id from subcategories where name = "Curva EMT"), 5600),
    ("Terminal EMT 1/2", (select id from subcategories where name = "Terminal EMT"), 1250),
    ("Terminal EMT 3/4", (select id from subcategories where name = "Terminal EMT"), 1600),
    ("Terminal EMT 1", (select id from subcategories where name = "Terminal EMT"), 2600),
    ("Canaleta eléctrica Dexon 13 x 7 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 8500),
    ("Canaleta eléctrica Dexon 20 x 12 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 11500),
    ("Canaleta eléctrica Dexon 20 x 20 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 14850),
    ("Canaleta eléctrica Dexon 32 x 12 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 24000),
    ("Canaleta eléctrica Dexon 25 x 25 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 22800),
    ("Canaleta eléctrica Dexon Piso x 2 metros", (select id from subcategories where name = "Canaleta eléctrica Dexon"), 39500),
    ("Canaleta eléctrica económica 13 x 7 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica económica"), 6800),
    ("Canaleta eléctrica económica 20 x 12 x 2 metros", (select id from subcategories where name = "Canaleta eléctrica económica"), 8500),
    ("Canaleta eléctrica económica Piso x 2 metros", (select id from subcategories where name = "Canaleta eléctrica económica"), 39500),
    ("Tapa externa Amazonas", (select id from subcategories where name = "Tapa externa"), 7800),
    ("Tapa externa Rango", (select id from subcategories where name = "Tapa externa"), 7800),
    ("Tapa interna Amazonas", (select id from subcategories where name = "Tapa interna"), 6800),
    ("Tapa interna Rango", (select id from subcategories where name = "Tapa interna"), 6800),
    ("Unión canal Amazonas", (select id from subcategories where name = "Unión canal"), 13600),
    ("Unión canal Rango", (select id from subcategories where name = "Unión canal"), 10200),
    ("Unión bajante Amazonas", (select id from subcategories where name = "Unión bajante"), 16800),
    ("Unión bajante Rango", (select id from subcategories where name = "Unión bajante"), 10900),
    ("Soporte canal Amazonas", (select id from subcategories where name = "Soporte canal"), 4500),
    ("Soporte canal Rango", (select id from subcategories where name = "Soporte canal"), 3500),
    ("Unión esquinera para canal Amazonas", (select id from subcategories where name = "Unión esquinera para canal"), 28500),
    ("Unión esquinera para canal Rango", (select id from subcategories where name = "Unión esquinera para canal"), 22000),
    ("Soporte de metal para canal Amazonas", (select id from subcategories where name = "Soporte de metal para canal"), 18500),
    ("Soporte de metal para canal Rango", (select id from subcategories where name = "Soporte de metal para canal"), 9700),
    ("Sello de caucho para canal Amazonas", (select id from subcategories where name = "Sello de caucho para canal"), 4800),
    ("Sello de caucho para canal Rango", (select id from subcategories where name = "Sello de caucho para canal"), 3600),
    ("Tubo bajante cuadrado x 3 metros", (select id from subcategories where name = "Tubo bajante cuadrado"), 43000),
    ("Canal Amazonas x 3 metros", (select id from subcategories where name = "Canal"), 62000),
    ("Canal Rango x 3 metros", (select id from subcategories where name = "Canal"), 44500),
    ("Tubo cortinero café 1/2 x 1 metro", (select id from subcategories where name = "Tubo cortinero café"), 4500),
    ("Tubo cortinero dorado 1/2 x 1 metro", (select id from subcategories where name = "Tubo cortinero dorado"), 4500),
    ("Tubo cortinero café 3/4 x 1 metro", (select id from subcategories where name = "Tubo cortinero café"), 6000),
    ("Tubo cortinero dorado 3/4 x 1 metro", (select id from subcategories where name = "Tubo cortinero dorado"), 6000),
    ("Tubo cortinero café 1", (select id from subcategories where name = "Tubo cortinero café"), 8500),
    ("Tubo cortinero dorado 1", (select id from subcategories where name = "Tubo cortinero dorado"), 8500),
    ("Soporte sencillo café 1/2", (select id from subcategories where name = "Soporte sencillo café"), 1000),
    ("Soporte sencillo dorado 1/2", (select id from subcategories where name = "Soporte sencillo dorado"), 1000),
    ("Soporte sencillo café 3/4", (select id from subcategories where name = "Soporte sencillo café"), 1200),
    ("Soporte sencillo dorado 3/4", (select id from subcategories where name = "Soporte sencillo dorado"), 1200),
    ("Soporte sencillo café 1", (select id from subcategories where name = "Soporte sencillo café"), 1500),
    ("Soporte sencillo dorado 1", (select id from subcategories where name = "Soporte sencillo dorado"), 1500),
    ("Soporte doble café 1/2", (select id from subcategories where name = "Soporte doble café"), 2100),
    ("Soporte doble dorado 1/2", (select id from subcategories where name = "Soporte doble dorado"), 2100),
    ("Soporte doble café 3/4", (select id from subcategories where name = "Soporte doble café"), 2900),
    ("Soporte doble dorado 3/4", (select id from subcategories where name = "Soporte doble dorado"), 2900),
    ("Soporte doble café 1", (select id from subcategories where name = "Soporte doble café"), 3500),
    ("Soporte doble dorado 1", (select id from subcategories where name = "Soporte doble dorado"), 3500),
    ("Plafón café 1/2", (select id from subcategories where name = "Plafón café"), 1000),
    ("Plafón dorado 1/2", (select id from subcategories where name = "Plafón dorado"), 1000),
    ("Plafón café 3/4", (select id from subcategories where name = "Plafón café"), 1200),
    ("Plafón dorado 3/4", (select id from subcategories where name = "Plafón dorado"), 1200),
    ("Plafón café 1", (select id from subcategories where name = "Plafón café"), 1500),
    ("Plafón dorado 1", (select id from subcategories where name = "Plafón dorado"), 1500),
    ("Perfiles de hierro calibre 18 1 x 1 x 6 metros", (select id from subcategories where name = "Perfiles de hierro calibre 18"), 34500),
    ("Perfiles de hierro calibre 18 2 x 1 x 6 metros", (select id from subcategories where name = "Perfiles de hierro calibre 18"), 44500),
    ("Perfiles de hierro calibre 18 3 x 1 1/2 x 6 metros", (select id from subcategories where name = "Perfiles de hierro calibre 18"), 64500),
    ("Perfiles de hierro calibre 20 3 x 1 1/2 x 6 metros", (select id from subcategories where name = "Perfiles de hierro calibre 20"), 54000),
    ("Ángulos de hierro calibre 18 3/4 x 1/8 x 6 metros", (select id from subcategories where name = "Ángulos de hierro calibre 18"), 26500),
    ("Ángulos de hierro calibre 18 1 x 1/8 x 6 metros", (select id from subcategories where name = "Ángulos de hierro calibre 18"), 34500),
    ("Ángulos de hierro calibre 20 1 x 1/8 x 6 metros", (select id from subcategories where name = "Ángulos de hierro calibre 20"), 10000),
    ("Platinas de hierro 1/8 x 1 x 6 metros", (select id from subcategories where name = "Platinas de hierro"), 10000),
    ("Platinas de hierro 1/8 x 1 x 1 metro", (select id from subcategories where name = "Platinas de hierro"), 28500),
    ("Platinas de hierro 1/8 x 1 1/2 x 6 metros", (select id from subcategories where name = "Platinas de hierro"), 39800),
    ("Platinas de hierro 1/8 x 1 1/2 x 1 metro", (select id from subcategories where name = "Platinas de hierro"), 13500),
    ("Malla plástica 15 x 15 negra x 1 metro", (select id from subcategories where name = "Mallas plásticas"), 7500),
    ("Angeo mosquetero", (select id from subcategories where name = "Mallas plásticas"), 7500),
    ("Malla 90 cm x rollo", (select id from subcategories where name = "Mallas galvanizadas"), 84000),
    ("Malla 90 cm x 1 metro", (select id from subcategories where name = "Mallas galvanizadas"), 3800),
    ("Malla 120 cm x rollo", (select id from subcategories where name = "Mallas galvanizadas"), 96000),
    ("Malla 120 cm x 1 metro", (select id from subcategories where name = "Mallas galvanizadas"), 4200),
    ("Malla 150 cm x rollo", (select id from subcategories where name = "Mallas galvanizadas"), 112000),
    ("Malla 150 cm x 1 metro", (select id from subcategories where name = "Mallas galvanizadas"), 5000),
    ("Malla 180 cm x rollo", (select id from subcategories where name = "Mallas galvanizadas"), 139000),
    ("Malla 180 cm x 1 metro", (select id from subcategories where name = "Mallas galvanizadas"), 6000),
    ("Piragua de aluminio wing x 6 metros", (select id from subcategories where name = "Piragua de aluminio"), 17900),
    ("Piragua de aluminio wing x 1 metro", (select id from subcategories where name = "Piragua de aluminio"), 4500),
    ("Piragua de aluminio normal x 6 metros", (select id from subcategories where name = "Piragua de aluminio"), 14800),
    ("Piragua de aluminio normal x 1 metro", (select id from subcategories where name = "Piragua de aluminio"), 3000),
    ("Cable duplex 2 x 18 x 1 metro", (select id from subcategories where name = "Cable duplex"), 2850),
    ("Cable duplex 2 x 16 x 1 metro", (select id from subcategories where name = "Cable duplex"), 3650),
    ("Cable duplex 2 x 14 x 1 metro", (select id from subcategories where name = "Cable duplex"), 4950),
    ("Cable duplex 2 x 12 x 1 metro", (select id from subcategories where name = "Cable duplex"), 6950),
    ("Alambre en barra #14 x 1 metro", (select id from subcategories where name = "Alambre en barra"), 1900),
    ("Alambre en barra #12 x 1 metro", (select id from subcategories where name = "Alambre en barra"), 2500),
    ("Alambre en barra #10 x 1 metro", (select id from subcategories where name = "Alambre en barra"), 4600),
    ("Alambre en barra #8 x 1 metro", (select id from subcategories where name = "Alambre en barra"), 6250),
    ("Cable 7 hilos #14 x 1 metro", (select id from subcategories where name = "Cable 7 hilos"), 2250),
    ("Cable 7 hilos #12 x 1 metro", (select id from subcategories where name = "Cable 7 hilos"), 3050),
    ("Cable 7 hilos #10 x 1 metro", (select id from subcategories where name = "Cable 7 hilos"), 4950),
    ("Cable 7 hilos #8 x 1 metro", (select id from subcategories where name = "Cable 7 hilos"), 6950),
    ("Alambre negro x kilo", (select id from subcategories where name = "Alambre negro"), 8500),
    ("Alambre negro x libra", (select id from subcategories where name = "Alambre negro"), 5000),
    ("Alambre galvanizado #18 x kilo", (select id from subcategories where name = "Alambre galvanizado"), 14500),
    ("Alambre galvanizado #18 x libra", (select id from subcategories where name = "Alambre galvanizado"), 8500),
    ("Alambre galvanizado #16 x kilo", (select id from subcategories where name = "Alambre galvanizado"), 14500),
    ("Alambre galvanizado #16 x libra", (select id from subcategories where name = "Alambre galvanizado"), 8500),
    ("Alambre galvanizado #14 x kilo", (select id from subcategories where name = "Alambre galvanizado"), 12000),
    ("Alambre galvanizado #14 x libra", (select id from subcategories where name = "Alambre galvanizado"), 7500),
    ("Alambre galvanizado #12 x kilo", (select id from subcategories where name = "Alambre galvanizado"), 10800),
    ("Alambre galvanizado #12 x libra", (select id from subcategories where name = "Alambre galvanizado"), 7500),
    ("Soldadura eléctrica Lincon 6013 x 3/32 Roja x kilo (64 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 20000),
    ("Soldadura eléctrica Lincon 6013 x 3/32 Roja x libra (32 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 10500),
    ("Soldadura eléctrica Lincon 6013 x 1/8 Roja x kilo (32 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 19800),
    ("Soldadura eléctrica Lincon 6013 x 1/8 Roja x libra (16 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 10500),
    ("Soldadura eléctrica Lincon 6011 x 3/32 Blanca x kilo (64 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 22000),
    ("Soldadura eléctrica Lincon 6011 x 3/32 Blanca x libra (32 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 12000),
    ("Soldadura eléctrica Lincon 6011 x 1/8 Blanca x kilo (32 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 20000),
    ("Soldadura eléctrica Lincon 6011 x 1/8 Blanca x libra (16 varillas)", (select id from subcategories where name = "Soldadura eléctrica Lincon"), 12000),
    ("Ángulo plástico normal", (select id from subcategories where name = "Ángulo plástico"), 3800),
    ("Ángulo plástico micro perforado", (select id from subcategories where name = "Ángulo plástico"), 7500),
    ("Zaranda de madera", (select id from subcategories where name = "Herramientas para construcción"), 32500),
    ("Valde negro", (select id from subcategories where name = "Herramientas para construcción"), 6500),
    ("Lavaplatos 1 x 50 solo", (select id from subcategories where name = "Lavaplatos"), 148000),
    ("Lavaplatos 1 x 50 completo", (select id from subcategories where name = "Lavaplatos"), 190000),
    ("Lavaplatos 60 x 40 solo", (select id from subcategories where name = "Lavaplatos"), 95000),
    ("Lavaplatos 60 x 40 completo", (select id from subcategories where name = "Lavaplatos"), 162000),
    ("Lavaplatos 50 x 40 solo", (select id from subcategories where name = "Lavaplatos"), 94000),
    ("Lavaplatos 50 x 40 completo", (select id from subcategories where name = "Lavaplatos"), 142000),
    ("Lavaplatos 62 x 48 solo", (select id from subcategories where name = "Lavaplatos"), 105000),
    ("Lavaplatos 62 x 48 completo", (select id from subcategories where name = "Lavaplatos"), 152000),
    ("Cable de acero trenzado 1/4 x metro", (select id from subcategories where name = "Cable de acero trenzado"), 4900),
    ("Cable de acero trenzado 1/8 x metro", (select id from subcategories where name = "Cable de acero trenzado"), 1500),
    ("Cable de acero trenzado 1/16 x metro", (select id from subcategories where name = "Cable de acero trenzado"), 950),
    ("Cable de acero trenzado 3/16 x metro", (select id from subcategories where name = "Cable de acero trenzado"), 3800),
    ("Bandeja para pintura económica", (select id from subcategories where name = "Bandejas para pintura"), 10000),
    ("Rodillo expóxico", (select id from subcategories where name = "Rodillos"), 19800),
    ("Rodillo de espuma", (select id from subcategories where name = "Rodillos"), 7500),
    ("Rodillo de felpa #9", (select id from subcategories where name = "Rodillos"), 8500),
    ("Rodillo de felpa #6", (select id from subcategories where name = "Rodillos"), 7500),
    ("Rodillo de felpa #5", (select id from subcategories where name = "Rodillos"), 5500),
    ("Rodillo de felpa #4", (select id from subcategories where name = "Rodillos"), 5200),
    ("Rodillo de felpa #3", (select id from subcategories where name = "Rodillos"), 5200),
    ("Rodillo de felpa #2", (select id from subcategories where name = "Rodillos"), 4800),
    ("Cordino #2", (select id from subcategories where name = "Cordino"), 650),
    ("Cordino #3", (select id from subcategories where name = "Cordino"), 750),
    ("Cordino #4", (select id from subcategories where name = "Cordino"), 950),
    ("Cordino #6", (select id from subcategories where name = "Cordino"), 1200),
    ("Cordino #8", (select id from subcategories where name = "Cordino"), 2200),
    ("Cordino #10", (select id from subcategories where name = "Cordino"), 2850),
    ("Cordino #12", (select id from subcategories where name = "Cordino"), 3250),
    ("Fibra plástica x 3000 metros", (select id from subcategories where name = "Fibra plástica"), 20500),
    ("Fibra plástica x 750 metros", (select id from subcategories where name = "Fibra plástica"), 17800),
    ("Fibra plástica amarilla", (select id from subcategories where name = "Fibra plástica"), 18500),
    ("Fibra plástica x 150 metros", (select id from subcategories where name = "Fibra plástica"), 4500),
    ("Fibra plástica 1/4", (select id from subcategories where name = "Fibra plástica"), 650),
    ("Fibra plástica 5/16", (select id from subcategories where name = "Fibra plástica"), 950),
    ("Fibra plástica 3/8", (select id from subcategories where name = "Fibra plástica"), 1200),
    ("Fibra plástica 1/2", (select id from subcategories where name = "Fibra plástica"), 1950),
    ("Cemento gris x bulto", (select id from subcategories where name = "Cemento"), 34900),
    ("Cemento gris x kilo", (select id from subcategories where name = "Cemento"), 1500),
    ("Cemento blanco x bulto", (select id from subcategories where name = "Cemento"), 86500),
    ("Cemento blanco x kilo", (select id from subcategories where name = "Cemento"), 3000),
    ("Estuco moldura x bulto", (select id from subcategories where name = "Estuco"), 44500),
    ("Estuco moldura x kilo", (select id from subcategories where name = "Estuco"), 2500),
    ("Estuco listo x bulto", (select id from subcategories where name = "Estuco"), 38000),
    ("Estuco listo x kilo", (select id from subcategories where name = "Estuco"), 2500),
    ("Estuco dinamo x bulto", (select id from subcategories where name = "Estuco"), 36000),
    ("Boquilla Corona Blanca x 2 kilos", (select id from subcategories where name = "Boquilla"), 15900),
    ("Boquilla Corona Beige x 2 kilos", (select id from subcategories where name = "Boquilla"), 15900),
    ("Boquilla Corona Gris x 2 kilos", (select id from subcategories where name = "Boquilla"), 16900),
    ("Boquilla Corona Negra x 2 kilos", (select id from subcategories where name = "Boquilla"), 16900),
    ("Boquilla Corona Tabaco x 2 kilos", (select id from subcategories where name = "Boquilla"), 16900),
    ("Alfaquik (Fijamix) x bulto", (select id from subcategories where name = "Pegaenchape y aditivos"), 22500),
    ("Broncosil x 2 kilos", (select id from subcategories where name = "Impermeabilizante en polvo"), 14000),
    ("Pegacerámica x bulto", (select id from subcategories where name = "Pegaenchape y aditivos"), 18000),
    ("Pegacerámica x kilo", (select id from subcategories where name = "Pegaenchape y aditivos"), 2000),
    ("Siflex P-10 x bulto", (select id from subcategories where name = "Impermeabilizante en polvo"), 18500),
    ("Yeso x kilo", (select id from subcategories where name = "Yeso"), 5000),
    ("Estuco Impadoc Obras x bulto", (select id from subcategories where name = "Estuco"), 38000),
    ("Estuco Impadoc Obras x 1/2 bulto", (select id from subcategories where name = "Estuco"), 22000),
    ("Estuco Impadoc Obras x kilo", (select id from subcategories where name = "Estuco"), 2500),
    ("Estuco Impadoc Listo x bulto", (select id from subcategories where name = "Estuco"), 44000),
    ("Estuco Impadoc Listo x 1/2 bulto", (select id from subcategories where name = "Estuco"), 25000),
    ("Estuco Impadoc Listo x kilo", (select id from subcategories where name = "Estuco"), 2500);